
sonar.projectKey=tk_customer_portal_web
sonar.sources=src
sonar.host.url=http://localhost:9001
sonar.login=admin
sonar.exclusions=.github/**, .vscode/** assets/**, build/**, node_modules/**, scripts/**, babel.config.js, index.js, commitlint.config.js, tests/setup.ts, reports-test/**, coverage/**, **/__test__/**, **/__tests__/*.test.ts, **/__mocks__/**, src/types/**
sonar.projectName=tk_customer_portal_web
sonar.projectVersion=1.0
sonar.login=admin
sonar.password=admin
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.test.ts.snap
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
